services:
  certbot:
    build: .
    container_name: certbot
    environment:
      - CLOUDFLARE_API_TOKEN
      - PRIMARY_DOMAIN
      - DOMAIN
      - EMAIL
      - BASE_CERT_PATH

    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certificates:/certificates
